Repository Final-healthree/healthree-backend, pull requests merged in 2022-10, with the labels that each got.

#216 PR : refactoring
  src/3_layers/controllers/goal.controller.js
  src/3_layers/controllers/video.controller.js
  src/3_layers/repositories/goal.repository.js
  src/3_layers/services/goal.service.js
  src/middlewares/goal.exception.middleware.js
  src/middlewares/video.exception.middleware.js
  src/routes/goal.routes.js
Labels: deployment

#220 PR : CORS test
  src/3_layers/controllers/comment.controller.js
  src/app.js
Labels: enhancement

#222 PR : Modify README.md
  README.md
  src/3_layers/controllers/goal.controller.js
Labels: enhancement

#225 PR : Update service architecture
  README.md
Labels: documentation

#227 PR : Modify kakao callback URL
  .gitignore
  README.md
  src/3_layers/services/goal.service.js
  src/app.js
  src/middlewares/goal.exception.middleware.js
  src/passport/kakao.strategy.js
Labels: enhancement

#228 PR : Modify kakao callback URL
  .gitignore
  README.md
  src/3_layers/services/goal.service.js
  src/app.js
  src/middlewares/goal.exception.middleware.js
  src/passport/kakao.strategy.js
Labels: enhancement

#230 PR : 비디오 병합 시간 속도 개선
  src/3_layers/controllers/video.controller.js
  src/3_layers/services/video.service.js
  src/modules/video.module.js
Labels: enhancement

#233 PR : Modify is_today_register
  .github/workflows/main.yml
  src/3_layers/repositories/goal.repository.js
  src/3_layers/services/goal.service.js
  src/middlewares/goal.exception.middleware.js
  src/middlewares/s3.middleware.js
  src/middlewares/video.exception.middleware.js
  src/modules/video.module.js
Labels: enhancement

#235 PR : Modify is_today_register
  .github/workflows/main.yml
Labels: enhancement

#236 PR : Modify video.module, video.service refactoring
  src/3_layers/services/video.service.js
  src/modules/video.module.js
Labels: enhancement

#237 PR : Modify video.module, video.service refactoring
  src/3_layers/services/video.service.js
  src/modules/video.module.js
Labels: enhancement
