Repository Final-healthree/healthree-backend, pull requests merged in 2022-09, with the labels that each got.

#5 PR : Merge for initailize
  package.json
  src/app.js
  src/controllers/main.controllers.js
  src/middlewares.js
  src/models/user.js
  src/repositories/main.repository.js
  src/routes/index.js
  src/routes/main.routes.js
  src/services/main.service.js
Labels: enhancement

#6 PR : PR before set `module`
  src/controllers/user.controller.js
  src/passport/index.js
  src/passport/kakaoStrategy.js
  src/routes/user.router.js
Labels: enhancement

#7 PR : Resolve app.js sequelize 선언문제 해결
  src/app.js
  src/controllers/main.controllers.js
  src/models/Ing.js
  src/models/Lose.js
  src/models/comment.js
  src/models/done.js
  src/models/index.js
  src/models/post.js
  src/models/user.js
  src/repositories/main.repository.js
  src/routes/main.routes.js
  src/services/main.service.js
Labels: enhancement

#10 PR : Create middlewares folder
  src/middlewares/s3_middlewares.js
Labels: enhancement

#11 PR : Create validation folder
  src/controllers/main.controllers.js
  src/repositories/main.repository.js
  src/routes/main.routes.js
  src/services/main.service.js
  src/validation/main.validation.js
Labels: enhancement

#13 PR : Add option of `models` about `unique: true`
  src/models/Ing.js
  src/models/Lose.js
  src/models/comment.js
  src/models/done.js
  src/models/post.js
  src/models/user.js
Labels: enhancement

#22 PR : Add cookie for jwt in `auth.router.js`
  src/app.js
  src/middlewares/auth.middleware.js
  src/routes/auth.router.js
Labels: enhancement

#26 PR : Test
  .gitignore
Labels: enhancement

#27 PR : Add PATCH api/main/video/:day/fail
  src/controllers/main.controllers.js
  src/repositories/main.repository.js
  src/routes/main.routes.js
  src/services/main.service.js
  src/validation/main.validation.js
Labels: enhancement

#28 PR : Modify `auth.controller.js`, `auth.middleware.js`,`auth.router.js`
  src/controllers/auth.controller.js
  src/middlewares/auth.middleware.js
  src/routes/auth.router.js
Labels: enhancement

#29 PR : Modify `users.routes.js`
  src/controllers/users.controller.js
  src/passport/kakaoStrategy.js
  src/routes/index.js
  src/routes/users.routes.js
Labels: enhancement

#32 PR : Modify `get_my_calnedar` of `users.repository.js`
  src/controllers/users.controller.js
  src/passport/kakaoStrategy.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
Labels: enhancement

#34 PR : `get_my_calendar` 구현 완료
  src/controllers/users.controller.js
  src/repositories/users.repository.js
  src/services/users.service.js
Labels: enhancement

#35 PR : Set `expiresInt of jwt`
  src/controllers/users.controller.js
Labels: enhancement

#37 PR : `get_my_videos` 구현 완료 및 주석 삭제
  src/controllers/users.controller.js
  src/services/users.service.js
Labels: enhancement

#38 PR : `share_my_video` 구현 완료
  src/controllers/users.controller.js
  src/models/goal.js
  src/repositories/main.repository.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
  src/validation/users.validation.js
Labels: enhancement

#40 Modify patch api/main/video/:day/fail and Modify s3.middlewares.js and Modify test code
  .gitignore
  package.json
  src/controllers/main.controller.js
  src/middlewares/s3.middleware.js
  src/routes/users.routes.js
  src/services/main.service.js
  src/validation/main.validation.js
  test/3_layers/main_controller.test.js
  test/3_layers/main_repository.test.js
  test/3_layers/main_service.test.js
  test/middlewares/s3_middleware.test.js
Labels: enhancement

#44 PR : Fix `Error` and `Exception` about `get_my_calendar`, `get_my_video`, `share_my_video`
  src/controllers/users.controller.js
  src/repositories/users.repository.js
  src/routes/users.routes.js
  src/services/users.service.js
  src/validation/users.validation.js
Labels: enhancement

#45 PR : Modify `users.service.js`
  src/services/users.service.js
Labels: enhancement

#46 PR : MVP용 first deployment
  .gitignore
  babel.config.json
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/controllers/index.html
  coverage/lcov-report/controllers/main.controller.js.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/middlewares/index.html
  coverage/lcov-report/middlewares/s3.middleware.js.html
  coverage/lcov-report/models/goal.js.html
  coverage/lcov-report/models/index.html
  coverage/lcov-report/models/user.js.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/repositories/index.html
  coverage/lcov-report/repositories/main.repository.js.html
  coverage/lcov-report/services/index.html
  coverage/lcov-report/services/main.service.js.html
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  jest.config.json
  package.json
  src/controllers/auth.controller.js
  src/controllers/main.controller.js
  src/controllers/users.controller.js
  src/middlewares/auth.middleware.js
  src/middlewares/s3.middleware.js
  src/models/goal.js
  src/passport/kakaoStrategy.js
  src/repositories/main.repository.js
  src/repositories/users.repository.js
  src/routes/auth.router.js
  src/routes/index.js
  src/routes/main.routes.js
  src/routes/users.routes.js
  src/services/main.service.js
  src/services/users.service.js
  src/validation/main.validation.js
  src/validation/users.validation.js
  test/3_layers/main_controller.test.js
  test/3_layers/main_repository.test.js
  test/3_layers/main_service.test.js
  test/middlewares/s3_middleware.test.js
Labels: deployment

#47 PR : Delete `.gitigonre` cache
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/controllers/index.html
  coverage/lcov-report/controllers/main.controller.js.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/middlewares/index.html
  coverage/lcov-report/middlewares/s3.middleware.js.html
  coverage/lcov-report/models/goal.js.html
  coverage/lcov-report/models/index.html
  coverage/lcov-report/models/user.js.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/repositories/index.html
  coverage/lcov-report/repositories/main.repository.js.html
  coverage/lcov-report/services/index.html
  coverage/lcov-report/services/main.service.js.html
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
Labels: enhancement

#49 PR : MVP용 deployment 2
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/controllers/index.html
  coverage/lcov-report/controllers/main.controller.js.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/middlewares/index.html
  coverage/lcov-report/middlewares/s3.middleware.js.html
  coverage/lcov-report/models/goal.js.html
  coverage/lcov-report/models/index.html
  coverage/lcov-report/models/user.js.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/repositories/index.html
  coverage/lcov-report/repositories/main.repository.js.html
  coverage/lcov-report/services/index.html
  coverage/lcov-report/services/main.service.js.html
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
Labels: deployment

#52 Refactoring `get_my_calendar`, `get_my_videos`, `share_my_video`
  src/controllers/users.controller.js
  src/repositories/users.repository.js
  src/services/users.service.js
Labels: enhancement

#53 PR : Modify 3계층 및 s3_middleware try catch 리팩토링
  .gitignore
  src/controllers/main.controller.js
  src/middlewares/s3.middleware.js
  src/repositories/main.repository.js
  src/validation/main.validation.js
  test/middlewares/s3_middleware.test.js
Labels: enhancement

#54 Revert "Refactoring `get_my_calendar`, `get_my_videos`, `share_my_video`"
  src/controllers/users.controller.js
  src/repositories/users.repository.js
  src/services/users.service.js
Labels: Mistake

#55 Re-merge : from dev/yu to develop
  src/controllers/users.controller.js
  src/repositories/users.repository.js
  src/services/users.service.js
  src/validation/users.validation.js
Labels: enhancement

#56 PR : Modify 폴더구조 리팩토링.. 3계층 폴더 취합
  src/3_layers/controllers/main.controller.js
  src/3_layers/controllers/users.controller.js
  src/3_layers/repositories/main.repository.js
  src/3_layers/repositories/users.repository.js
  src/3_layers/services/main.service.js
  src/3_layers/services/users.service.js
  src/routes/main.routes.js
  src/routes/users.routes.js
  test/3_layers/main_controller.test.js
  test/3_layers/main_repository.test.js
  test/3_layers/main_service.test.js
Labels: enhancement

#60 PR : Add validation.test.js 작성
  .gitignore
  package.json
  src/3_layers/controllers/main.controller.js
  src/3_layers/controllers/users.controller.js
  src/3_layers/repositories/main.repository.js
  src/3_layers/repositories/users.repository.js
  src/3_layers/services/main.service.js
  src/3_layers/services/users.service.js
  src/middlewares/s3.middleware.js
  src/repositories/main.repository.js
  src/repositories/users.repository.js
  src/routes/main.routes.js
  src/routes/users.routes.js
  src/services/users.service.js
  src/validation/main.validation.js
  src/validation/users.validation.js
  test/3_layers/main_controller.test.js
  test/3_layers/main_repository.test.js
  test/3_layers/main_service.test.js
  test/middlewares/s3_middleware.test.js
  test/validation/main.validation.test.js
Labels: enhancement

#61 PR : Add attribute `get_my_videos` of `users.repository.js`
  src/3_layers/controllers/users.controller.js
  src/3_layers/repositories/users.repository.js
  src/3_layers/services/users.service.js
Labels: enhancement

#62 PR : Add attribute `get_my_videos` of `users.repository.js` on `dev/yu`
  src/3_layers/controllers/users.controller.js
  src/3_layers/repositories/users.repository.js
  src/3_layers/services/users.service.js
Labels: enhancement

#67 PR : Add `front server` on `users.controller.js` of `dev/yu`
  src/3_layers/controllers/users.controller.js
Labels: enhancement

#68 PR : Add `front server` on `users.controller.js` for
  src/3_layers/controllers/users.controller.js
Labels: deployment

#72 PR :
  src/app.js
Labels: enhancement

#73 PR : Add `cors_white_list`
  src/app.js
Labels: deployment

#74 PR : Modify `cors error`
  src/app.js
Labels: enhancement

#75 PR : Modify `cors error`
  src/app.js
Labels: deployment

#76 PR : cors error
  src/app.js
Labels: bug

#77 PR : cors error
  src/app.js
Labels: bug

#78 PR : Modify `kakao_redirect`
  src/3_layers/controllers/users.controller.js
Labels: enhancement

#79 PR : Modify `kakao_redirect`
  src/3_layers/controllers/users.controller.js
Labels: enhancement

#80 PR : Modify `kakao_redirect`
  src/3_layers/controllers/users.controller.js
Labels: enhancement

#81 PR : Modify `kakao_redirect`
  src/3_layers/controllers/users.controller.js
Labels: enhancement

#85 PR : Modify api/main/goal_day/:day => api/main/goal_day
  package.json
  src/3_layers/controllers/main.controller.js
  src/3_layers/repositories/main.repository.js
  src/3_layers/services/main.service.js
  src/app.js
  src/routes/main.routes.js
  src/validation/main.validation.js
  test/middlewares/s3.middleware.test.js
Labels: enhancement

#86 PR : Modify `kakao_redirect_url`
  src/3_layers/controllers/users.controller.js
Labels: enhancement

#87 PR : Modify `kakao_redirect_url`
  src/3_layers/controllers/users.controller.js
Labels: enhancement

#88 Modify `users.controller.js`, `auth.middleware.js`
  src/3_layers/controllers/users.controller.js
  src/middlewares/auth.middleware.js
Labels: enhancement

#89 PR : Modify `users.controller.js`, `auth.middleware.js`
  src/3_layers/controllers/users.controller.js
  src/middlewares/auth.middleware.js
Labels: enhancement

#90 PR : Modify `kakao_redirectUrl`
  src/3_layers/controllers/users.controller.js
  src/3_layers/repositories/users.repository.js
  src/3_layers/services/users.service.js
  src/middlewares/auth.middleware.js
Labels: enhancement

#91 PR : Modify `kakao_redirectUrl`
  src/3_layers/controllers/users.controller.js
  src/3_layers/repositories/users.repository.js
  src/3_layers/services/users.service.js
  src/middlewares/auth.middleware.js
Labels: enhancement

#92 Modify `users.service.js`, `users.repository.js`
  src/3_layers/repositories/users.repository.js
  src/3_layers/services/users.service.js
Labels: enhancement

#93 PR : Modify `users.service.js`, `users.repository.js`
  src/3_layers/repositories/users.repository.js
  src/3_layers/services/users.service.js
Labels: enhancement

#94 PR : Refoctoring `users.service.js`, `users.repository.js`
  src/3_layers/repositories/users.repository.js
  src/3_layers/services/users.service.js
Labels: enhancement

#95 PR : Refactoring `users.service.js`, `users.repository.js`
  src/3_layers/repositories/users.repository.js
  src/3_layers/services/users.service.js
Labels: deployment

#96 PR : refactoring directory
  package.json
  src/3_layers/controllers/auth.controller.js
  src/3_layers/controllers/goal.controller.js
  src/3_layers/controllers/main.controller.js
  src/3_layers/controllers/users.controller.js
  src/3_layers/controllers/video.controller.js
  src/3_layers/repositories/goal.repository.js
  src/3_layers/repositories/users.repository.js
  src/3_layers/repositories/video.repository.js
  src/3_layers/services/goal.service.js
  src/3_layers/services/main.service.js
  src/3_layers/services/users.service.js
  src/3_layers/services/video.service.js
  src/middlewares/auth.middleware.js
  src/middlewares/goal.exception.middleware.js
  src/middlewares/s3.middleware.js
  src/middlewares/video.exception.middleware.js
  src/modules/video.module.js
  src/passport/kakaoStrategy.js
  src/routes/auth.routes.js
  src/routes/goal.routes.js
  src/routes/index.js
  src/routes/main.routes.js
  src/routes/users.routes.js
  src/routes/video.routes.js
  src/validation/users.validation.js
  test/3_layers/main_controller.test.js
  test/3_layers/main_repository.test.js
  test/3_layers/main_service.test.js
  test/validation/main.validation.test.js
Labels: enhancement

#97 PR : Create `swagger`
  package.json
  src/app.js
  src/passport/index.js
  src/swagger/goal.ui.js
  src/swagger/swagger.js
Labels: enhancement

#100 PR : Modify database
  src/app.js
  src/middlewares/goal.exception.middleware.js
  src/middlewares/video.exception.middleware.js
  src/models/goal.js
  src/models/video.js
Labels: enhancement

#101 PR : Modify and refactoring
  src/3_layers/controllers/goal.controller.js
  src/3_layers/repositories/goal.repository.js
  src/3_layers/repositories/video.repository.js
  src/3_layers/services/goal.service.js
  src/3_layers/services/video.service.js
  src/middlewares/goal.exception.middleware.js
  src/middlewares/video.exception.middleware.js
Labels: enhancement

#103 PR : Modifying and refactoring
  src/3_layers/controllers/goal.controller.js
  src/3_layers/repositories/goal.repository.js
  src/3_layers/repositories/video.repository.js
  src/3_layers/services/goal.service.js
  src/3_layers/services/video.service.js
  src/app.js
  src/middlewares/goal.exception.middleware.js
  src/middlewares/video.exception.middleware.js
  src/models/goal.js
  src/models/video.js
  src/passport/index.js
  src/passport/kakaoStrategy.js
Labels: enhancement, deployment

#105 PR : Install module `gl`
  package.json
Labels: enhancement, deployment

#108 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#109 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#110 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#111 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#112 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#113 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#115 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#117 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#118 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#119 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#120 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#121 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#122 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#123 PR : Modify video.module.js => 해상도 변경
  src/modules/video.module.js
Labels: enhancement

#125 PR : Set config file `pm2` with `xvfb`
  src/process.json
Labels: enhancement

#126 PR : Set config file `pm2` with `xvfb`
  src/process.json
Labels: enhancement, deployment

#127 PR : Modify dotenv path
  .github/workflows/main.yml
  package.json
  src/3_layers/controllers/auth.controller.js
  src/app.js
  src/config/config.js
  src/middlewares/auth.middleware.js
  src/modules/video.module.js
  src/passport/kakaoStrategy.js
Labels: enhancement

#128 PR : Modify dotenv path
  .github/workflows/main.yml
  package.json
  src/3_layers/controllers/auth.controller.js
  src/app.js
  src/config/config.js
  src/middlewares/auth.middleware.js
  src/modules/video.module.js
  src/passport/kakaoStrategy.js
Labels: enhancement

#129 PR : Modify process.json
  package.json
  process.json
Labels: enhancement

#130 PR : Modify process.json
  package.json
  process.json
Labels: enhancement

#131 PR : Delete module `cookie-parser`
  package.json
Labels: enhancement

#132 PR : Delete module `cookie-parser`
  package.json
Labels: deployment, refactoring

#133 PR : Add main.yml
  .github/workflows/main.yml
Labels: enhancement

#134 PR : Add main.yml
  .github/workflows/main.yml
Labels: enhancement

#135 PR : CI/CD 설정
  .github/workflows/main.yml
  appspec.yml
  scripts/after-deploy.sh
Labels: enhancement

#136 PR : CI/CD 설정
  .github/workflows/main.yml
  appspec.yml
  scripts/after-deploy.sh
Labels: enhancement

#137 PR : CI/CD success
  .github/workflows/main.yml
  scripts/after-deploy.sh
Labels: deployment

#139 PR : CI/CD success
  .github/workflows/main.yml
Labels: deployment

#140 PR : CI/CD success
  .github/workflows/main.yml
Labels: deployment

#141 PR : CI/CD test
  scripts/after-deploy.sh
Labels: enhancement

#142 PR : CI/CD test
  scripts/after-deploy.sh
Labels: enhancement

#144 PR : CI/CD success
  scripts/after-deploy.sh
Labels: enhancement

#145 PR : CORS white List 작성
  src/app.js
Labels: deployment

#146 PR : CORS white List 작성
  src/app.js
Labels: enhancement

#149 PR : Add api/goals/exist 진행중인 작심삼일이 존재하는지 여부
  scripts/after-deploy.sh
  src/3_layers/controllers/goal.controller.js
  src/3_layers/repositories/goal.repository.js
  src/3_layers/services/goal.service.js
  src/app.js
  src/routes/goal.routes.js
Labels: enhancement

#150 PR : Add api/goals/exist 진행중인 작심삼일이 존재하는지 여부
  scripts/after-deploy.sh
  src/3_layers/controllers/goal.controller.js
  src/3_layers/repositories/goal.repository.js
  src/3_layers/services/goal.service.js
  src/app.js
  src/routes/goal.routes.js
Labels: enhancement

#151 PR : Change some details
  src/3_layers/controllers/goal.controller.js
  src/3_layers/controllers/video.controller.js
  src/passport/kakao.strategy.js
Labels: enhancement

#152 PR : Change some details
  src/3_layers/controllers/goal.controller.js
  src/3_layers/controllers/video.controller.js
  src/passport/kakao.strategy.js
Labels: deployment

#153 PR : Modify import kakao strategy
  src/passport/index.js
Labels: enhancement

#154 PR : Modify import kakao strategy
  src/passport/index.js
Labels: deployment

#156 PR : Set `routes`
  src/routes/comment.routes.js
  src/routes/index.js
  src/routes/post.routes.js
Labels: enhancement

#157 PR : Modify `src/routes/comment.routes.js`, `src/routes/post.routes.js`
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
  src/routes/comment.routes.js
  src/routes/post.routes.js
Labels: enhancement

#158 Revert "PR : Modify `src/routes/comment.routes.js`, `src/routes/post.routes.js`"
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
  src/routes/comment.routes.js
  src/routes/post.routes.js
Labels: revert

#159 PR : Modify `src/routes/comment.routes.js`, `src/routes/post.routes.js`
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
  src/routes/comment.routes.js
  src/routes/post.routes.js
Labels: enhancement

#160 PR : Modify `src/routes/comment.routes.js`, `src/routes/post.routes.js`
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
  src/routes/comment.routes.js
  src/routes/post.routes.js
Labels: deployment

#162 PR : Modify app.js cors test
  src/3_layers/repositories/goal.repository.js
  src/3_layers/services/goal.service.js
  src/app.js
Labels: bug

#163 PR : Create `Post`
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
  src/middlewares/post.exception.middleware.js
  src/middlewares/video.exception.middleware.js
  src/models/comment.js
  src/models/post.js
  src/models/user.js
  src/routes/post.routes.js
Labels: enhancement

#164 PR : Create `Post`
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
  src/middlewares/post.exception.middleware.js
  src/middlewares/video.exception.middleware.js
  src/models/comment.js
  src/models/post.js
  src/models/user.js
  src/routes/post.routes.js
Labels: deployment

#165 PR : Add Comment CRUD 구현 완료
  src/3_layers/controllers/comment.controller.js
  src/3_layers/repositories/comment.repository.js
  src/3_layers/services/comment.service.js
  src/middlewares/comment.exception.middleware.js
  src/models/comment.js
  src/models/post.js
  src/models/user.js
  src/routes/comment.routes.js
Labels: enhancement

#167 PR : Modify `redirect_url`
  src/3_layers/controllers/auth.controller.js
  src/3_layers/repositories/post.repository.js
  src/models/comment.js
  src/models/user.js
Labels: enhancement

#168 PR : Modify `redirect_url`
  src/3_layers/controllers/auth.controller.js
  src/3_layers/repositories/post.repository.js
  src/models/comment.js
  src/models/user.js
Labels: deployment

#169 PR : Modify some details `Post`
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
  src/middlewares/post.exception.middleware.js
  src/models/post.js
  src/models/user.js
Labels: enhancement

#170 PR : Modify some details `Post`
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
  src/middlewares/post.exception.middleware.js
  src/models/post.js
  src/models/user.js
Labels: deployment

#171 PR : Add rank.controller.js
  src/3_layers/controllers/rank.controller.js
  src/middlewares/comment.exception.middleware.js
  src/middlewares/goal.exception.middleware.js
  src/models/comment.js
  src/models/post.js
  src/models/user.js
  src/routes/index.js
  src/routes/rank.routes.js
Labels: enhancement

#173 PR : Add rank.controller.js
  src/3_layers/controllers/rank.controller.js
  src/middlewares/comment.exception.middleware.js
  src/middlewares/goal.exception.middleware.js
  src/models/comment.js
  src/models/post.js
  src/models/user.js
  src/routes/index.js
  src/routes/rank.routes.js
Labels: enhancement

#175 PR : Add rank.controller.js
  src/3_layers/controllers/rank.controller.js
Labels: enhancement

#176 PR : Add rank.controller.js
  src/models/comment.js
  src/models/post.js
  src/models/user.js
Labels: enhancement

#178 PR : Fixing error commit
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
  src/models/post.js
  src/models/user.js
Labels: enhancement

#179 PR : error git pull main
  src/3_layers/controllers/rank.controller.js
  src/middlewares/goal.exception.middleware.js
  src/routes/index.js
  src/routes/rank.routes.js
Labels: enhancement

#177 PR : Add rank.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
  src/middlewares/comment.exception.middleware.js
  src/middlewares/goal.exception.middleware.js
  src/models/post.js
Labels: enhancement

#180 PR : Add rank.controller.js
  src/3_layers/controllers/rank.controller.js
  src/routes/index.js
  src/routes/rank.routes.js
Labels: enhancement

#181 PR : Add rank.controller.js
  src/3_layers/controllers/rank.controller.js
  src/routes/index.js
  src/routes/rank.routes.js
Labels: enhancement

#183 PR : Delete `remark`, Modify `post.service.js`
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
Labels: enhancement

#184 PR : Delete `remark`, Modify `post.service.js`
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
Labels: deployment

#185 PR : Refactoring `Post`
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
  src/middlewares/auth.middleware.js
  src/middlewares/post.exception.middleware.js
  src/routes/post.routes.js
Labels: enhancement

#186 PR : Refactoring `Post`
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/post.service.js
  src/middlewares/auth.middleware.js
  src/middlewares/post.exception.middleware.js
  src/routes/post.routes.js
Labels: deployment

#189 PR : Modify model
  src/combine/2414289968.mp4
  src/combine/editly-tmp-cd1azb8To3CW9liwM58ot/audio-mixed.flac
Labels: enhancement

#190 PR : Modify model
  src/combine/2414289968.mp4
  src/combine/editly-tmp-cd1azb8To3CW9liwM58ot/audio-mixed.flac
Labels: enhancement

#192 PR : Add video.modules.js => thumbnail create
  .github/workflows/main.yml
  package.json
  src/3_layers/controllers/rank.controller.js
  src/3_layers/repositories/goal.repository.js
  src/3_layers/repositories/video.repository.js
  src/3_layers/services/goal.service.js
  src/3_layers/services/video.service.js
  src/middlewares/auth.middleware.js
  src/models/user.js
  src/modules/video.module.js
  src/passport/kakao.strategy.js
Labels: enhancement

#193 PR : Add video.modules.js => thumbnail create
  .github/workflows/main.yml
  package.json
  src/3_layers/controllers/rank.controller.js
  src/3_layers/repositories/goal.repository.js
  src/3_layers/repositories/video.repository.js
  src/3_layers/services/goal.service.js
  src/3_layers/services/video.service.js
  src/middlewares/auth.middleware.js
  src/models/user.js
  src/modules/video.module.js
  src/passport/kakao.strategy.js
Labels: enhancement

#194 PR : Refactoring and Create `Post`, `Exceptions`
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/repositories/video.repository.js
  src/3_layers/services/post.service.js
  src/exception/custom.exception.js
  src/exceptionhandler/exception.handler.js
  src/middlewares/post.exception.middleware.js
  src/routes/post.routes.js
Labels: enhancement

#195 PR : Refactoring and Create `Post`, `Exceptions`
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/repositories/video.repository.js
  src/3_layers/services/post.service.js
  src/exception/custom.exception.js
  src/exceptionhandler/exception.handler.js
  src/middlewares/post.exception.middleware.js
  src/routes/post.routes.js
Labels: enhancement

#196 PR : Add attribute `thumbnail`
  src/3_layers/services/post.service.js
  src/3_layers/services/video.service.js
Labels: enhancement

#197 PR : Add attribute `thumbnail`
  src/3_layers/services/post.service.js
  src/3_layers/services/video.service.js
Labels: enhancement

#198 PR : Modify details `Post`
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/goal.service.js
  src/3_layers/services/post.service.js
  src/middlewares/post.exception.middleware.js
  src/routes/post.routes.js
Labels: enhancement

#199 PR : Modify details `Post`
  src/3_layers/controllers/post.controller.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/goal.service.js
  src/3_layers/services/post.service.js
  src/middlewares/post.exception.middleware.js
  src/routes/post.routes.js
Labels: enhancement

#200 PR : Modify `kakao_redirectURL`
  src/passport/kakao.strategy.js
Labels: enhancement

#201 PR : Modify `kakao_redirectURL`
  src/passport/kakao.strategy.js
Labels: enhancement

#202 PR : Modify comment
  src/3_layers/repositories/comment.repository.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/comment.service.js
  src/3_layers/services/post.service.js
  src/app.js
  src/middlewares/comment.exception.middleware.js
  src/models/comment.js
  src/modules/video.module.js
Labels: deployment

#203 PR : Modify comment
  src/3_layers/repositories/comment.repository.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/services/comment.service.js
  src/3_layers/services/post.service.js
  src/app.js
  src/middlewares/comment.exception.middleware.js
  src/models/comment.js
  src/modules/video.module.js
Labels: deployment

#205 PR : deployment
  .github/workflows/main.yml
  src/3_layers/controllers/goal.controller.js
  src/3_layers/controllers/video.controller.js
  src/3_layers/repositories/comment.repository.js
  src/3_layers/repositories/goal.repository.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/repositories/video.repository.js
  src/3_layers/services/goal.service.js
  src/middlewares/goal.exception.middleware.js
  src/middlewares/video.exception.middleware.js
Labels: deployment

#206 PR : deployment
  .github/workflows/main.yml
  src/3_layers/controllers/goal.controller.js
  src/3_layers/controllers/video.controller.js
  src/3_layers/repositories/comment.repository.js
  src/3_layers/repositories/goal.repository.js
  src/3_layers/repositories/post.repository.js
  src/3_layers/repositories/video.repository.js
  src/3_layers/services/goal.service.js
  src/middlewares/goal.exception.middleware.js
  src/middlewares/video.exception.middleware.js
Labels: deployment

#207 PR : deploymet UT 배포
  .github/workflows/main.yml
  .gitignore
  src/3_layers/controllers/auth.controller.js
  src/3_layers/controllers/goal.controller.js
  src/3_layers/services/goal.service.js
  src/3_layers/services/post.service.js
  src/middlewares/goal.exception.middleware.js
  src/middlewares/video.exception.middleware.js
Labels: deployment

#208 PR : deploymet UT 배포
  .github/workflows/main.yml
  .gitignore
  src/3_layers/controllers/auth.controller.js
  src/3_layers/controllers/goal.controller.js
  src/3_layers/services/goal.service.js
  src/3_layers/services/post.service.js
  src/middlewares/goal.exception.middleware.js
  src/middlewares/video.exception.middleware.js
Labels: deployment

#209 PR : deploymet UT 배포
  .github/workflows/main.yml
Labels: deployment

#210 PR : deploymet UT 배포
  .github/workflows/main.yml
Labels: deployment

#214 PR : Modify 예외처리 해제
  .gitignore
  src/middlewares/goal.exception.middleware.js
  src/middlewares/video.exception.middleware.js
Labels: deployment

#215 PR : Modify status code
  src/3_layers/controllers/auth.controller.js
  src/3_layers/controllers/comment.controller.js
  src/3_layers/controllers/goal.controller.js
  src/3_layers/controllers/post.controller.js
  src/3_layers/controllers/rank.controller.js
  src/3_layers/controllers/video.controller.js
  src/middlewares/comment.exception.middleware.js
  src/middlewares/goal.exception.middleware.js
  src/middlewares/post.exception.middleware.js
  src/middlewares/video.exception.middleware.js
  src/passport/kakao.strategy.js
Labels: enhancement
